
name: Tests
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'corretto'
        cache: gradle
    - name: Setup firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'
    - run: firefox --version
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run chmod to make geckodriver executable
      run: chmod +x resources/geckodriver
      
    - name: Run Tests
      run: ./gradlew test
